# Generated by Django 3.1.7 on 2021-03-13 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationType',
            fields=[
                ('_id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('completed', models.BooleanField(auto_created=True, default=False, editable=False)),
                ('date', models.DateField(auto_created=True, auto_now=True)),
                ('_id', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.donationtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
